### PR TITLE
MySQL

### PR DESCRIPTION
**Pull request by ManalShaikh**
Please make it into mysqli or PDO. mysql_connect doesn't work anymore.

### CODE REVIEW

**Comment by therecluse26** [comment]
Could you please explain what the purpose of this pull request is? It looks like you're just replacing PDO with the older, less-secure mysqli library.

**Comment by therecluse26** [comment]
This already uses PDO, it doesn’t use mysql_connect... where are you getting that idea?
  

  
  

  
  
>

**Comment by ManalShaikh** [comment]
I'll need to recheck. The last time I saw was Mysql_connect

**Comment by therecluse26** [comment]
It's not, but thank you.

**Pull request closed without merging**
