### PR TITLE
Refactor authorization and fix ajax API authorization

### PR DESCRIPTION
**Pull request by daniel-falk**
Fixes:

* #160 Authorization for admin ajax APIs
* Bug regarding refurl infinite loop preventing users from logging in
* Bug regarding IP-address of remote to prevent stolen sessions
* Bug regarding missing exit after header redirect

See the commit messages for more info. Correct me if I'm wrong regarding the IP-address check or something else.

### CODE REVIEW

**Comment by therecluse26** [comment]
Thanks @daniel-falk ! Pulling these in locally to test them, and I'll merge them in once I've verified everything

**Comment by therecluse26** [comment]
Excellent addition @daniel-falk 

Fixing this was actually one of the things I had on my personal to do list, so thank you!

**Comment by daniel-falk** [comment]
Cool! I'll probably send you a mail later - I'm thinking about how to make the integration between the top menu and the application the login-system is used in easier... I don't have much "pride" in making it "my way", so I rather try to pull the project in the same way as you are.

**Comment by therecluse26** [comment]
Sounds good to me! I'm flexible as well, I have a bunch of other projects going on at once, so I definitely appreciate the help. If you look in the "projects" section, I have a few rough ideas in there if you want look through some of those and add some of your own and we can take a look. Based on the quality of some of these additions, I'd definitely feel comfortable adding you as a collaborator if you're interested?

**Pull request merged**
